const admin = require("firebase-admin");
const serviceAccount = require("./serviceAccountKey.json");

admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
const db = admin.firestore();

const foods = [
  // ── FAST FOOD ──────────────────────────────────────────────────────────────
  { id: "pizza", category: "fast_food", name: "Pizza" },
  { id: "burger", category: "fast_food", name: "Burger" },
  { id: "fries", category: "fast_food", name: "Fries" },
  { id: "hot_dog", category: "fast_food", name: "Hot Dog" },
  { id: "chicken_wings", category: "fast_food", name: "Chicken Wings" },
  { id: "fried_chicken", category: "fast_food", name: "Fried Chicken" },
  { id: "nachos", category: "fast_food", name: "Nachos" },
  { id: "onion_rings", category: "fast_food", name: "Onion Rings" },
  { id: "cheeseburger", category: "fast_food", name: "Cheeseburger" },
  { id: "fish_burger", category: "fast_food", name: "Fish Burger" },
  { id: "chicken_sandwich", category: "fast_food", name: "Chicken Sandwich" },
  { id: "loaded_fries", category: "fast_food", name: "Loaded Fries" },
  { id: "chicken_nuggets", category: "fast_food", name: "Chicken Nuggets" },
  { id: "wrap", category: "fast_food", name: "Wrap" },
  { id: "pulled_pork_sandwich", category: "fast_food", name: "Pulled Pork Sandwich" },
  { id: "smash_burger", category: "fast_food", name: "Smash Burger" },
  { id: "philly_cheesesteak", category: "fast_food", name: "Philly Cheesesteak" },
  { id: "mozzarella_sticks", category: "fast_food", name: "Mozzarella Sticks" },
  { id: "buffalo_wings", category: "fast_food", name: "Buffalo Wings" },
  { id: "deep_dish_pizza", category: "fast_food", name: "Deep Dish Pizza" },
  { id: "calzone", category: "fast_food", name: "Calzone" },
  { id: "garlic_bread", category: "fast_food", name: "Garlic Bread" },
  { id: "chicken_tenders", category: "fast_food", name: "Chicken Tenders" },
  { id: "gyros", category: "fast_food", name: "Gyros" },
  { id: "doner_kebab", category: "fast_food", name: "Döner Kebab" },

  // ── MEAT ───────────────────────────────────────────────────────────────────
  { id: "steak", category: "meat", name: "Steak" },
  { id: "bbq_ribs", category: "meat", name: "BBQ Ribs" },
  { id: "lamb_chops", category: "meat", name: "Lamb Chops" },
  { id: "roast_beef", category: "meat", name: "Roast Beef" },
  { id: "pork_belly", category: "meat", name: "Pork Belly" },
  { id: "rack_of_lamb", category: "meat", name: "Rack of Lamb" },
  { id: "beef_tenderloin", category: "meat", name: "Beef Tenderloin" },
  { id: "duck_breast", category: "meat", name: "Duck Breast" },
  { id: "venison", category: "meat", name: "Venison" },
  { id: "brisket", category: "meat", name: "Brisket" },
  { id: "beef_stew", category: "meat", name: "Beef Stew" },
  { id: "lamb_tagine", category: "meat", name: "Lamb Tagine" },
  { id: "beef_kebab", category: "meat", name: "Beef Kebab" },
  { id: "pork_chop", category: "meat", name: "Pork Chop" },
  { id: "beef_bourguignon", category: "meat", name: "Beef Bourguignon" },
  { id: "coq_au_vin", category: "meat", name: "Coq au Vin" },
  { id: "grilled_chicken", category: "meat", name: "Grilled Chicken" },
  { id: "chorizo", category: "meat", name: "Chorizo" },
  { id: "beef_wellington", category: "meat", name: "Beef Wellington" },
  { id: "lamb_shank", category: "meat", name: "Lamb Shank" },
  { id: "carnitas", category: "meat", name: "Carnitas" },
  { id: "short_rib", category: "meat", name: "Braised Short Rib" },
  { id: "oxtail", category: "meat", name: "Oxtail Stew" },
  { id: "beef_cheeks", category: "meat", name: "Braised Beef Cheeks" },
  { id: "slow_roast_pork", category: "meat", name: "Slow Roast Pork" },

  // ── SEAFOOD ────────────────────────────────────────────────────────────────
  { id: "sushi", category: "seafood", name: "Sushi" },
  { id: "fish_and_chips", category: "seafood", name: "Fish and Chips" },
  { id: "grilled_salmon", category: "seafood", name: "Grilled Salmon" },
  { id: "oysters", category: "seafood", name: "Oysters" },
  { id: "lobster", category: "seafood", name: "Lobster" },
  { id: "shrimp_cocktail", category: "seafood", name: "Shrimp Cocktail" },
  { id: "crab_cakes", category: "seafood", name: "Crab Cakes" },
  { id: "tuna_steak", category: "seafood", name: "Tuna Steak" },
  { id: "sea_bass", category: "seafood", name: "Sea Bass" },
  { id: "mussels", category: "seafood", name: "Mussels" },
  { id: "clam_chowder", category: "seafood", name: "Clam Chowder" },
  { id: "scallops", category: "seafood", name: "Scallops" },
  { id: "calamari", category: "seafood", name: "Calamari" },
  { id: "smoked_salmon", category: "seafood", name: "Smoked Salmon" },
  { id: "prawn_curry", category: "seafood", name: "Prawn Curry" },
  { id: "fish_tacos", category: "seafood", name: "Fish Tacos" },
  { id: "ceviche", category: "seafood", name: "Ceviche" },
  { id: "bouillabaisse", category: "seafood", name: "Bouillabaisse" },
  { id: "sashimi", category: "seafood", name: "Sashimi" },
  { id: "lobster_bisque", category: "seafood", name: "Lobster Bisque" },
  { id: "crab_linguine", category: "seafood", name: "Crab Linguine" },
  { id: "tempura_prawns", category: "seafood", name: "Tempura Prawns" },
  { id: "grilled_sardines", category: "seafood", name: "Grilled Sardines" },
  { id: "prawn_risotto", category: "seafood", name: "Prawn Risotto" },
  { id: "lobster_thermidor", category: "seafood", name: "Lobster Thermidor" },

  // ── ITALIAN ────────────────────────────────────────────────────────────────
  { id: "pasta", category: "italian", name: "Pasta" },
  { id: "lasagna", category: "italian", name: "Lasagna" },
  { id: "risotto", category: "italian", name: "Risotto" },
  { id: "carbonara", category: "italian", name: "Carbonara" },
  { id: "cacio_e_pepe", category: "italian", name: "Cacio e Pepe" },
  { id: "gnocchi", category: "italian", name: "Gnocchi" },
  { id: "tiramisu", category: "italian", name: "Tiramisu" },
  { id: "bruschetta", category: "italian", name: "Bruschetta" },
  { id: "arancini", category: "italian", name: "Arancini" },
  { id: "spaghetti_bolognese", category: "italian", name: "Spaghetti Bolognese" },
  { id: "parmigiana", category: "italian", name: "Parmigiana di Melanzane" },
  { id: "focaccia", category: "italian", name: "Focaccia" },
  { id: "burrata", category: "italian", name: "Burrata" },
  { id: "caprese", category: "italian", name: "Caprese Salad" },
  { id: "pizza_margherita", category: "italian", name: "Pizza Margherita" },
  { id: "ravioli", category: "italian", name: "Ravioli" },
  { id: "linguine_vongole", category: "italian", name: "Linguine alle Vongole" },
  { id: "squid_ink_risotto", category: "italian", name: "Squid Ink Risotto" },
  { id: "pappardelle_truffle", category: "italian", name: "Pappardelle al Tartufo" },
  { id: "ossobuco_main", category: "italian", name: "Ossobuco" },
  { id: "bistecca_fiorentina", category: "italian", name: "Bistecca alla Fiorentina" },
  { id: "pizza_four_cheese", category: "italian", name: "Pizza Quattro Formaggi" },
  { id: "minestrone", category: "italian", name: "Minestrone" },
  { id: "pesto_pasta", category: "italian", name: "Pesto Pasta" },
  { id: "cannoli", category: "italian", name: "Cannoli" },

  // ── MEXICAN ────────────────────────────────────────────────────────────────
  { id: "tacos", category: "mexican", name: "Tacos" },
  { id: "enchiladas", category: "mexican", name: "Enchiladas" },
  { id: "quesadillas", category: "mexican", name: "Quesadillas" },
  { id: "guacamole", category: "mexican", name: "Guacamole" },
  { id: "burritos", category: "mexican", name: "Burritos" },
  { id: "tamales", category: "mexican", name: "Tamales" },
  { id: "chiles_rellenos", category: "mexican", name: "Chiles Rellenos" },
  { id: "mole_negro", category: "mexican", name: "Mole Negro" },
  { id: "carne_asada", category: "mexican", name: "Carne Asada" },
  { id: "churros", category: "mexican", name: "Churros" },
  { id: "cochinita_pibil", category: "mexican", name: "Cochinita Pibil" },
  { id: "birria_tacos", category: "mexican", name: "Birria Tacos" },
  { id: "taco_al_pastor", category: "mexican", name: "Tacos al Pastor" },
  { id: "chiles_en_nogada", category: "mexican", name: "Chiles en Nogada" },
  { id: "agua_chile", category: "mexican", name: "Aguachile" },

  // ── ASIAN ──────────────────────────────────────────────────────────────────
  { id: "pad_thai", category: "asian", name: "Pad Thai" },
  { id: "dim_sum", category: "asian", name: "Dim Sum" },
  { id: "peking_duck", category: "asian", name: "Peking Duck" },
  { id: "ramen", category: "asian", name: "Ramen" },
  { id: "spring_rolls", category: "asian", name: "Spring Rolls" },
  { id: "fried_rice", category: "asian", name: "Fried Rice" },
  { id: "kung_pao_chicken", category: "asian", name: "Kung Pao Chicken" },
  { id: "dumplings", category: "asian", name: "Dumplings" },
  { id: "pho", category: "asian", name: "Pho" },
  { id: "bibimbap", category: "asian", name: "Bibimbap" },
  { id: "bulgogi", category: "asian", name: "Bulgogi" },
  { id: "green_curry", category: "asian", name: "Green Curry" },
  { id: "nasi_goreng", category: "asian", name: "Nasi Goreng" },
  { id: "laksa", category: "asian", name: "Laksa" },
  { id: "satay", category: "asian", name: "Satay" },
  { id: "banh_mi", category: "asian", name: "Bánh Mì" },
  { id: "red_curry", category: "asian", name: "Red Curry" },
  { id: "massaman_curry", category: "asian", name: "Massaman Curry" },
  { id: "bao_buns", category: "asian", name: "Bao Buns" },
  { id: "sichuan_hotpot", category: "asian", name: "Sichuan Hot Pot" },
  { id: "rendang", category: "asian", name: "Rendang" },
  { id: "korean_fried_chicken", category: "asian", name: "Korean Fried Chicken" },
  { id: "gyoza", category: "asian", name: "Gyoza" },
  { id: "som_tum", category: "asian", name: "Som Tum" },
  { id: "pad_see_ew", category: "asian", name: "Pad See Ew" },

  // ── INDIAN ─────────────────────────────────────────────────────────────────
  { id: "butter_chicken", category: "indian", name: "Butter Chicken" },
  { id: "biryani", category: "indian", name: "Biryani" },
  { id: "saag_paneer", category: "indian", name: "Saag Paneer" },
  { id: "chana_masala", category: "indian", name: "Chana Masala" },
  { id: "dal_makhani", category: "indian", name: "Dal Makhani" },
  { id: "vindaloo", category: "indian", name: "Vindaloo" },
  { id: "korma", category: "indian", name: "Lamb Korma" },
  { id: "samosas", category: "indian", name: "Samosas" },
  { id: "tikka_masala", category: "indian", name: "Chicken Tikka Masala" },
  { id: "rogan_josh", category: "indian", name: "Rogan Josh" },
  { id: "dosa", category: "indian", name: "Dosa" },
  { id: "tandoori_chicken", category: "indian", name: "Tandoori Chicken" },
  { id: "pav_bhaji", category: "indian", name: "Pav Bhaji" },
  { id: "seekh_kebab", category: "indian", name: "Seekh Kebab" },
  { id: "lamb_biryani", category: "indian", name: "Lamb Biryani" },

  // ── MIDDLE EASTERN ─────────────────────────────────────────────────────────
  { id: "hummus", category: "middle_eastern", name: "Hummus" },
  { id: "falafel", category: "middle_eastern", name: "Falafel" },
  { id: "shawarma", category: "middle_eastern", name: "Shawarma" },
  { id: "kebab", category: "middle_eastern", name: "Kebab" },
  { id: "tabbouleh", category: "middle_eastern", name: "Tabbouleh" },
  { id: "baba_ganoush", category: "middle_eastern", name: "Baba Ganoush" },
  { id: "shakshuka", category: "middle_eastern", name: "Shakshuka" },
  { id: "mezze", category: "middle_eastern", name: "Mezze Platter" },
  { id: "kibbeh", category: "middle_eastern", name: "Kibbeh" },
  { id: "chicken_shawarma", category: "middle_eastern", name: "Chicken Shawarma" },
  { id: "baklava", category: "middle_eastern", name: "Baklava" },
  { id: "mansaf", category: "middle_eastern", name: "Mansaf" },
  { id: "musakhan", category: "middle_eastern", name: "Musakhan" },
  { id: "knafeh", category: "middle_eastern", name: "Knafeh" },
  { id: "fattoush", category: "middle_eastern", name: "Fattoush" },

  // ── SPANISH ────────────────────────────────────────────────────────────────
  { id: "paella", category: "spanish", name: "Paella" },
  { id: "tapas", category: "spanish", name: "Tapas" },
  { id: "gazpacho", category: "spanish", name: "Gazpacho" },
  { id: "tortilla_espanola", category: "spanish", name: "Tortilla Española" },
  { id: "jamon_iberico", category: "spanish", name: "Jamón Ibérico" },
  { id: "patatas_bravas", category: "spanish", name: "Patatas Bravas" },
  { id: "croquetas", category: "spanish", name: "Croquetas" },
  { id: "gambas_al_ajillo", category: "spanish", name: "Gambas al Ajillo" },
  { id: "pan_con_tomate", category: "spanish", name: "Pan con Tomate" },
  { id: "pulpo_gallego", category: "spanish", name: "Pulpo a la Gallega" },
  { id: "albondigas", category: "spanish", name: "Albóndigas" },
  { id: "pimientos_padron", category: "spanish", name: "Pimientos de Padrón" },
  { id: "fabada_asturiana", category: "spanish", name: "Fabada Asturiana" },
  { id: "bacalao_pil_pil", category: "spanish", name: "Bacalao al Pil Pil" },
  { id: "cocido_madrileño", category: "spanish", name: "Cocido Madrileño" },

  // ── HEALTHY ────────────────────────────────────────────────────────────────
  { id: "caesar_salad", category: "healthy", name: "Caesar Salad" },
  { id: "quinoa_bowl", category: "healthy", name: "Quinoa Bowl" },
  { id: "avocado_toast", category: "healthy", name: "Avocado Toast" },
  { id: "nicoise_salad", category: "healthy", name: "Niçoise Salad" },
  { id: "greek_salad", category: "healthy", name: "Greek Salad" },
  { id: "buddha_bowl", category: "healthy", name: "Buddha Bowl" },
  { id: "poke_bowl", category: "healthy", name: "Poke Bowl" },
  { id: "cobb_salad", category: "healthy", name: "Cobb Salad" },
  { id: "lentil_soup", category: "healthy", name: "Lentil Soup" },
  { id: "kale_salad", category: "healthy", name: "Kale Salad" },
  { id: "gado_gado", category: "healthy", name: "Gado Gado" },
  { id: "watermelon_feta", category: "healthy", name: "Watermelon & Feta Salad" },
  { id: "chickpea_salad", category: "healthy", name: "Chickpea Salad" },
  { id: "edamame", category: "healthy", name: "Edamame" },
  { id: "acai_bowl", category: "healthy", name: "Açaí Bowl" },

  // ── BREAKFAST ──────────────────────────────────────────────────────────────
  { id: "full_english", category: "breakfast", name: "Full English" },
  { id: "eggs_benedict", category: "breakfast", name: "Eggs Benedict" },
  { id: "pancakes", category: "breakfast", name: "Pancakes" },
  { id: "french_toast", category: "breakfast", name: "French Toast" },
  { id: "waffles", category: "breakfast", name: "Waffles" },
  { id: "smoked_salmon_bagel", category: "breakfast", name: "Smoked Salmon Bagel" },
  { id: "oatmeal", category: "breakfast", name: "Porridge" },
  { id: "croque_monsieur", category: "breakfast", name: "Croque Monsieur" },
  { id: "crepes", category: "breakfast", name: "Crêpes" },
  { id: "biscuits_gravy", category: "breakfast", name: "Biscuits and Gravy" },
  { id: "breakfast_burrito", category: "breakfast", name: "Breakfast Burrito" },
  { id: "congee", category: "breakfast", name: "Congee" },
  { id: "chilaquiles", category: "breakfast", name: "Chilaquiles" },
  { id: "ful_medames", category: "breakfast", name: "Ful Medames" },
  { id: "omelette", category: "breakfast", name: "Omelette" },

  // ── SNACKS ─────────────────────────────────────────────────────────────────
  { id: "cheese_board", category: "snack", name: "Cheese Board" },
  { id: "charcuterie", category: "snack", name: "Charcuterie Board" },
  { id: "pretzels", category: "snack", name: "Pretzels" },
  { id: "devilled_eggs", category: "snack", name: "Devilled Eggs" },
  { id: "spinach_dip", category: "snack", name: "Spinach Artichoke Dip" },
  { id: "scotch_eggs", category: "snack", name: "Scotch Eggs" },
  { id: "pate_toast", category: "snack", name: "Pâté on Toast" },
  { id: "tzatziki_pita", category: "snack", name: "Tzatziki and Pita" },
  { id: "antipasto", category: "snack", name: "Antipasto" },
  { id: "olives", category: "snack", name: "Marinated Olives" },
  { id: "nuts_mix", category: "snack", name: "Bar Nuts" },
  { id: "nachos_snack", category: "snack", name: "Nachos" },
  { id: "pigs_blankets", category: "snack", name: "Pigs in Blankets" },
  { id: "popcorn", category: "snack", name: "Popcorn" },
  { id: "bread_cheese", category: "snack", name: "Bread and Cheese" },

  // ── DESSERT ────────────────────────────────────────────────────────────────
  { id: "chocolate_cake", category: "dessert", name: "Chocolate Cake" },
  { id: "creme_brulee", category: "dessert", name: "Crème Brûlée" },
  { id: "cheesecake", category: "dessert", name: "Cheesecake" },
  { id: "apple_pie", category: "dessert", name: "Apple Pie" },
  { id: "sticky_toffee_pudding", category: "dessert", name: "Sticky Toffee Pudding" },
  { id: "tarte_tatin", category: "dessert", name: "Tarte Tatin" },
  { id: "profiteroles", category: "dessert", name: "Profiteroles" },
  { id: "eton_mess", category: "dessert", name: "Eton Mess" },
  { id: "pavlova", category: "dessert", name: "Pavlova" },
  { id: "baklava_dessert", category: "dessert", name: "Baklava" },
  { id: "tarte_au_citron", category: "dessert", name: "Lemon Tart" },
  { id: "mousse_au_chocolat", category: "dessert", name: "Chocolate Mousse" },
  { id: "mochi", category: "dessert", name: "Mochi" },
  { id: "panna_cotta_dessert", category: "dessert", name: "Panna Cotta" },
  { id: "bread_butter_pudding", category: "dessert", name: "Bread and Butter Pudding" },

  // ── GREEK ──────────────────────────────────────────────────────────────────
  { id: "moussaka", category: "greek", name: "Moussaka" },
  { id: "souvlaki", category: "greek", name: "Souvlaki" },
  { id: "spanakopita", category: "greek", name: "Spanakopita" },
  { id: "stifado", category: "greek", name: "Stifado" },
  { id: "kleftiko", category: "greek", name: "Kleftiko" },
  { id: "dolmades", category: "greek", name: "Dolmades" },
  { id: "saganaki", category: "greek", name: "Saganaki" },
  { id: "pastitsio", category: "greek", name: "Pastitsio" },
  { id: "keftedes", category: "greek", name: "Keftedes" },
  { id: "horiatiki", category: "greek", name: "Horiatiki Salad" },

  // ── FRENCH ─────────────────────────────────────────────────────────────────
  { id: "french_onion_soup", category: "french", name: "French Onion Soup" },
  { id: "duck_confit", category: "french", name: "Duck Confit" },
  { id: "croissant", category: "french", name: "Croissant" },
  { id: "boeuf_bourguignon", category: "french", name: "Boeuf Bourguignon" },
  { id: "escargot", category: "french", name: "Escargots" },
  { id: "foie_gras", category: "french", name: "Foie Gras" },
  { id: "quiche_lorraine", category: "french", name: "Quiche Lorraine" },
  { id: "steak_frites", category: "french", name: "Steak Frites" },
  { id: "ratatouille", category: "french", name: "Ratatouille" },
  { id: "cassoulet", category: "french", name: "Cassoulet" },
  { id: "bouillabaisse_f", category: "french", name: "Bouillabaisse" },
  { id: "tartiflette", category: "french", name: "Tartiflette" },
  { id: "gratin_dauphinois", category: "french", name: "Gratin Dauphinois" },
  { id: "tarte_flambee", category: "french", name: "Tarte Flambée" },
  { id: "crepes_suzette", category: "french", name: "Crêpes Suzette" },

  // ── JAPANESE ───────────────────────────────────────────────────────────────
  { id: "tonkatsu", category: "japanese", name: "Tonkatsu" },
  { id: "yakitori", category: "japanese", name: "Yakitori" },
  { id: "takoyaki", category: "japanese", name: "Takoyaki" },
  { id: "okonomiyaki", category: "japanese", name: "Okonomiyaki" },
  { id: "katsu_curry", category: "japanese", name: "Katsu Curry" },
  { id: "udon", category: "japanese", name: "Udon" },
  { id: "gyoza_jp", category: "japanese", name: "Gyoza" },
  { id: "shabu_shabu", category: "japanese", name: "Shabu-Shabu" },
  { id: "karaage", category: "japanese", name: "Karaage" },
  { id: "zaru_soba", category: "japanese", name: "Zaru Soba" },
  { id: "agedashi_tofu", category: "japanese", name: "Agedashi Tofu" },

  // ── AMERICAN ───────────────────────────────────────────────────────────────
  { id: "mac_cheese", category: "american", name: "Mac and Cheese" },
  { id: "bbq_pulled_pork", category: "american", name: "BBQ Pulled Pork" },
  { id: "new_england_chowder", category: "american", name: "New England Chowder" },
  { id: "lobster_roll", category: "american", name: "Lobster Roll" },
  { id: "smoked_brisket", category: "american", name: "Texas Brisket" },
  { id: "reuben_sandwich", category: "american", name: "Reuben Sandwich" },
  { id: "gumbo", category: "american", name: "Gumbo" },
  { id: "key_lime_pie", category: "american", name: "Key Lime Pie" },
  { id: "crab_boil", category: "american", name: "Crab Boil" },
  { id: "cheesesteak", category: "american", name: "Philly Cheesesteak" },

  // ── BARBECUE ───────────────────────────────────────────────────────────────
  { id: "bbq_chicken", category: "barbecue", name: "BBQ Chicken" },
  { id: "smoked_sausage", category: "barbecue", name: "Smoked Sausage" },
  { id: "spare_ribs", category: "barbecue", name: "Spare Ribs" },
  { id: "burnt_ends", category: "barbecue", name: "Burnt Ends" },
  { id: "smoked_wings", category: "barbecue", name: "Smoked Wings" },
  { id: "pulled_chicken", category: "barbecue", name: "Pulled Chicken" },
  { id: "bbq_corn", category: "barbecue", name: "Grilled Corn" },

  // ── CARIBBEAN ──────────────────────────────────────────────────────────────
  { id: "jerk_chicken", category: "caribbean", name: "Jerk Chicken" },
  { id: "curry_goat", category: "caribbean", name: "Curry Goat" },
  { id: "ackee_saltfish", category: "caribbean", name: "Ackee and Saltfish" },
  { id: "plantain", category: "caribbean", name: "Fried Plantain" },
  { id: "rice_peas", category: "caribbean", name: "Rice and Peas" },

  // ── GERMAN ─────────────────────────────────────────────────────────────────
  { id: "bratwurst", category: "german", name: "Bratwurst" },
  { id: "schnitzel", category: "german", name: "Wiener Schnitzel" },
  { id: "sauerbraten", category: "german", name: "Sauerbraten" },
  { id: "currywurst", category: "german", name: "Currywurst" },
  { id: "black_forest_cake", category: "german", name: "Black Forest Cake" },
  { id: "pretzel_german", category: "german", name: "Soft Pretzel" },
  { id: "kartoffelsalat", category: "german", name: "Kartoffelsalat" },

  // ── SOUTH AMERICAN ─────────────────────────────────────────────────────────
  { id: "asado", category: "south_american", name: "Asado" },
  { id: "empanadas", category: "south_american", name: "Empanadas" },
  { id: "ceviche_peruvian", category: "south_american", name: "Ceviche Peruano" },
  { id: "lomo_saltado", category: "south_american", name: "Lomo Saltado" },
  { id: "feijoada", category: "south_american", name: "Feijoada" },
  { id: "arepas", category: "south_american", name: "Arepas" },
  { id: "churrasco", category: "south_american", name: "Churrasco" },

  // ── MOROCCAN ───────────────────────────────────────────────────────────────
  { id: "lamb_tagine_moroccan", category: "moroccan", name: "Lamb Tagine" },
  { id: "couscous_moroccan", category: "moroccan", name: "Seven Vegetable Couscous" },
  { id: "bastilla", category: "moroccan", name: "Bastilla" },
  { id: "harira", category: "moroccan", name: "Harira" },

  // ── EASTERN EUROPEAN ───────────────────────────────────────────────────────
  { id: "pierogi", category: "eastern_european", name: "Pierogi" },
  { id: "borscht", category: "eastern_european", name: "Borscht" },
  { id: "goulash", category: "eastern_european", name: "Goulash" },
  { id: "stroganoff", category: "eastern_european", name: "Beef Stroganoff" },
  { id: "blini", category: "eastern_european", name: "Blini" },
  { id: "pelmeni", category: "eastern_european", name: "Pelmeni" },

  // ── CAJUN ──────────────────────────────────────────────────────────────────
  { id: "jambalaya", category: "cajun", name: "Jambalaya" },
  { id: "etouffe", category: "cajun", name: "Crawfish Étouffée" },
  { id: "red_beans_rice", category: "cajun", name: "Red Beans and Rice" },
  { id: "po_boy", category: "cajun", name: "Po'boy" },
  { id: "gumbo_cajun", category: "cajun", name: "Cajun Gumbo" },

  // ── VEGETARIAN ─────────────────────────────────────────────────────────────
  { id: "mushroom_risotto", category: "vegetarian", name: "Mushroom Risotto" },
  { id: "veggie_burger", category: "vegetarian", name: "Veggie Burger" },
  { id: "stuffed_peppers", category: "vegetarian", name: "Stuffed Peppers" },
  { id: "cauliflower_steak", category: "vegetarian", name: "Cauliflower Steak" },
  { id: "vegetable_tagine", category: "vegetarian", name: "Vegetable Tagine" },
  { id: "lentil_dhal", category: "vegetarian", name: "Lentil Dhal" },
  { id: "falafel_wrap", category: "vegetarian", name: "Falafel Wrap" },
  { id: "shakshuka_v", category: "vegetarian", name: "Shakshuka" },
];

const alcohols = [
  { id: "lager", name: "Lager", type: "beer" },
  { id: "ipa", name: "IPA", type: "beer" },
  { id: "stout", name: "Stout", type: "beer" },
  { id: "cider", name: "Cider", type: "beer" },
  { id: "pale_ale", name: "Pale Ale", type: "beer" },
  { id: "wheat_beer", name: "Wheat Beer", type: "beer" },
  { id: "porter", name: "Porter", type: "beer" },
  { id: "red_wine", name: "Red Wine", type: "wine" },
  { id: "white_wine", name: "White Wine", type: "wine" },
  { id: "rose_wine", name: "Rosé Wine", type: "wine" },
  { id: "champagne", name: "Champagne", type: "wine" },
  { id: "sake", name: "Sake", type: "wine" },
  { id: "prosecco", name: "Prosecco", type: "wine" },
  { id: "sauvignon_blanc", name: "Sauvignon Blanc", type: "wine" },
  { id: "chardonnay", name: "Chardonnay", type: "wine" },
  { id: "pinot_noir", name: "Pinot Noir", type: "wine" },
  { id: "cabernet_sauvignon", name: "Cabernet Sauvignon", type: "wine" },
  { id: "riesling", name: "Riesling", type: "wine" },
  { id: "malbec", name: "Malbec", type: "wine" },
  { id: "port", name: "Port", type: "wine" },
  { id: "sherry", name: "Sherry", type: "wine" },
  { id: "whiskey", name: "Whiskey", type: "spirit" },
  { id: "vodka", name: "Vodka", type: "spirit" },
  { id: "rum", name: "Rum", type: "spirit" },
  { id: "gin", name: "Gin", type: "spirit" },
  { id: "tequila", name: "Tequila", type: "spirit" },
  { id: "bourbon", name: "Bourbon", type: "spirit" },
  { id: "mezcal", name: "Mezcal", type: "spirit" },
  { id: "cognac", name: "Cognac", type: "spirit" },
  { id: "bloody_mary", name: "Bloody Mary", type: "cocktail" },
  { id: "mojito", name: "Mojito", type: "cocktail" },
  { id: "margarita", name: "Margarita", type: "cocktail" },
  { id: "old_fashioned", name: "Old Fashioned", type: "cocktail" },
  { id: "martini", name: "Martini", type: "cocktail" },
  { id: "negroni", name: "Negroni", type: "cocktail" },
  { id: "sangria", name: "Sangria", type: "cocktail" },
  { id: "mimosa", name: "Mimosa", type: "cocktail" },
  { id: "aperol_spritz", name: "Aperol Spritz", type: "cocktail" },
  { id: "gin_tonic", name: "Gin and Tonic", type: "cocktail" },
  { id: "moscow_mule", name: "Moscow Mule", type: "cocktail" },
];

const pairings = [
  // Fast Food
  { foodId: "pizza", alcoholId: "lager", reason: "Crisp carbonation cuts through melted cheese and tangy tomato sauce." },
  { foodId: "pizza", alcoholId: "red_wine", reason: "Medium-bodied red matches the acidity of tomato and richness of toppings." },
  { foodId: "pizza", alcoholId: "ipa", reason: "Hoppy bitterness balances the fat from cheese and cured meats." },
  { foodId: "burger", alcoholId: "lager", reason: "Light carbonation refreshes the palate between rich, juicy bites." },
  { foodId: "burger", alcoholId: "ipa", reason: "Bold hops cut through the fat of beef and melted cheese." },
  { foodId: "burger", alcoholId: "cabernet_sauvignon", reason: "Firm tannins stand up beautifully to the richness of the beef." },
  { foodId: "fries", alcoholId: "lager", reason: "Cold, crisp lager is the classic partner for salty golden fries." },
  { foodId: "fries", alcoholId: "cider", reason: "Fruity acidity lifts the saltiness and cuts the oil." },
  { foodId: "fries", alcoholId: "pale_ale", reason: "Light malt sweetness complements the potato without overpowering." },
  { foodId: "hot_dog", alcoholId: "lager", reason: "A cold lager is the quintessential match for a ballpark hot dog." },
  { foodId: "hot_dog", alcoholId: "cider", reason: "Apple notes echo the sweetness of the sausage and mustard." },
  { foodId: "chicken_wings", alcoholId: "ipa", reason: "Resinous hops tame the heat and cut through the sticky sauce." },
  { foodId: "chicken_wings", alcoholId: "lager", reason: "Ice-cold carbonation soothes the spice and refreshes between bites." },
  { foodId: "chicken_wings", alcoholId: "pale_ale", reason: "Gentle bitterness balances the tangy buffalo sauce perfectly." },
  { foodId: "fried_chicken", alcoholId: "lager", reason: "Crisp bubbles cut through the richness of the fried crust." },
  { foodId: "fried_chicken", alcoholId: "champagne", reason: "Fine bubbles and acidity contrast beautifully with fried richness." },
  { foodId: "fried_chicken", alcoholId: "pale_ale", reason: "Malt body complements the crust while hops balance the fat." },
  { foodId: "nachos", alcoholId: "lager", reason: "Cold lager refreshes between the layers of cheese and jalapeño." },
  { foodId: "nachos", alcoholId: "margarita", reason: "Lime and tequila are natural partners for Mexican-spiced nachos." },
  { foodId: "nachos", alcoholId: "tequila", reason: "Agave spirit echoes the smoky, spiced flavours of the dish." },
  { foodId: "cheeseburger", alcoholId: "lager", reason: "Classic pairing — cold lager cuts through double cheese and sauce." },
  { foodId: "cheeseburger", alcoholId: "ipa", reason: "Hop bitterness balances the fat from beef and melted cheddar." },
  { foodId: "cheeseburger", alcoholId: "bourbon", reason: "Caramel notes in bourbon mirror the charred, caramelised beef." },
  { foodId: "buffalo_wings", alcoholId: "ipa", reason: "Citrusy hops tame the cayenne heat of the buffalo sauce." },
  { foodId: "buffalo_wings", alcoholId: "lager", reason: "Effervescence cools the burn and refreshes with every wing." },
  { foodId: "philly_cheesesteak", alcoholId: "lager", reason: "Light lager balances the rich, savoury ribeye and cheese." },
  { foodId: "philly_cheesesteak", alcoholId: "ipa", reason: "Hop bitterness cuts through the richness of the cheese sauce." },
  { foodId: "gyros", alcoholId: "lager", reason: "Crisp lager refreshes against the herb-spiced rotisserie meat." },
  { foodId: "gyros", alcoholId: "rose_wine", reason: "Dry rosé echoes the Mediterranean flavours of the dish." },
  { foodId: "doner_kebab", alcoholId: "lager", reason: "Cold lager is the classic late-night partner for a döner." },
  { foodId: "doner_kebab", alcoholId: "red_wine", reason: "Spiced lamb flavours are complemented by a medium red wine." },
  { foodId: "deep_dish_pizza", alcoholId: "red_wine", reason: "A bold red stands up to the thick tomato sauce and cheese." },
  { foodId: "deep_dish_pizza", alcoholId: "lager", reason: "Carbonation cuts through the dense, doughy richness." },
  { foodId: "garlic_bread", alcoholId: "white_wine", reason: "Crisp white wine cuts through the butter and complements garlic." },
  { foodId: "garlic_bread", alcoholId: "lager", reason: "Light lager refreshes the palate between buttery bites." },

  // Meat
  { foodId: "steak", alcoholId: "cabernet_sauvignon", reason: "Classic match — firm tannins bind with the fat and protein in beef." },
  { foodId: "steak", alcoholId: "malbec", reason: "Dark fruit and plum notes complement the char and richness of steak." },
  { foodId: "steak", alcoholId: "whiskey", reason: "Smoky warmth mirrors the caramelised crust of a well-seared steak." },
  { foodId: "bbq_ribs", alcoholId: "stout", reason: "Roasted malt in stout echoes the smoky, dark bark of the ribs." },
  { foodId: "bbq_ribs", alcoholId: "whiskey", reason: "Smoky sweetness in whiskey harmonises with the sticky barbecue glaze." },
  { foodId: "bbq_ribs", alcoholId: "bourbon", reason: "Vanilla and caramel in bourbon mirror the sweet, charred sauce." },
  { foodId: "lamb_chops", alcoholId: "red_wine", reason: "Earthy red wine complements the gamey sweetness of lamb." },
  { foodId: "lamb_chops", alcoholId: "cabernet_sauvignon", reason: "Bold tannins cut through the fat and enhance the herb crust." },
  { foodId: "roast_beef", alcoholId: "cabernet_sauvignon", reason: "Structured tannins and dark fruit are the perfect match for roast beef." },
  { foodId: "roast_beef", alcoholId: "red_wine", reason: "A medium-bodied red brings out the savoury depth of the roast." },
  { foodId: "pork_belly", alcoholId: "cider", reason: "Apple acidity cuts through the rich rendered fat beautifully." },
  { foodId: "pork_belly", alcoholId: "pinot_noir", reason: "Light-bodied red with cherry notes complements without overwhelming." },
  { foodId: "duck_breast", alcoholId: "pinot_noir", reason: "Silky Pinot Noir is the classic partner for rich, pink duck breast." },
  { foodId: "duck_breast", alcoholId: "cognac", reason: "French brandy echoes the richness and brings out the cherry notes." },
  { foodId: "venison", alcoholId: "cabernet_sauvignon", reason: "Bold tannins match the lean, intensely flavoured game meat." },
  { foodId: "venison", alcoholId: "porter", reason: "Dark malt and roasted notes complement the earthiness of venison." },
  { foodId: "brisket", alcoholId: "bourbon", reason: "Vanilla and oak in bourbon mirror the smoke of a 12-hour brisket." },
  { foodId: "brisket", alcoholId: "stout", reason: "Roasted malt depth echoes the dark bark and smoky richness." },
  { foodId: "brisket", alcoholId: "red_wine", reason: "Full-bodied red stands up to the intense, slow-cooked beef." },
  { foodId: "beef_stew", alcoholId: "red_wine", reason: "Red wine in the stew and in the glass creates perfect harmony." },
  { foodId: "beef_stew", alcoholId: "stout", reason: "Dark malt flavours deepen the savoury, slow-cooked beef." },
  { foodId: "lamb_tagine", alcoholId: "red_wine", reason: "Earthy red wine ties together the warm spices and lamb." },
  { foodId: "lamb_tagine", alcoholId: "rose_wine", reason: "Dry rosé bridges the sweet fruit and savoury spiced broth." },
  { foodId: "beef_kebab", alcoholId: "lager", reason: "Cold lager refreshes between bites of chargrilled spiced beef." },
  { foodId: "beef_kebab", alcoholId: "red_wine", reason: "Medium red wine complements the cumin and paprika spicing." },
  { foodId: "beef_bourguignon", alcoholId: "red_wine", reason: "What's cooked in it goes with it — Burgundy is the perfect match." },
  { foodId: "beef_bourguignon", alcoholId: "pinot_noir", reason: "Earthy depth mirrors the mushrooms and slow-braised beef." },
  { foodId: "coq_au_vin", alcoholId: "red_wine", reason: "The wine in the braise and in the glass creates seamless harmony." },
  { foodId: "coq_au_vin", alcoholId: "pinot_noir", reason: "Light tannins and red fruit echo the lardons and thyme." },
  { foodId: "grilled_chicken", alcoholId: "white_wine", reason: "Crisp white wine lifts the lemon and herb flavours of the chicken." },
  { foodId: "grilled_chicken", alcoholId: "chardonnay", reason: "Buttery Chardonnay complements the char and juiciness of the breast." },
  { foodId: "beef_wellington", alcoholId: "cabernet_sauvignon", reason: "Bold tannins cut through the buttery pastry and rich beef." },
  { foodId: "beef_wellington", alcoholId: "red_wine", reason: "A full red wine is worthy of this classic showstopper." },
  { foodId: "lamb_shank", alcoholId: "red_wine", reason: "Slow-braised lamb and a full red wine are a natural match." },
  { foodId: "lamb_shank", alcoholId: "malbec", reason: "Deep purple fruit in Malbec echoes the richness of the braised shank." },
  { foodId: "short_rib", alcoholId: "cabernet_sauvignon", reason: "Bold tannins stand up to the collagen-rich, slow-braised richness." },
  { foodId: "short_rib", alcoholId: "bourbon", reason: "Caramel and vanilla notes mirror the sticky, reduced braising liquid." },
  { foodId: "oxtail", alcoholId: "red_wine", reason: "Earthy red wine deepens the gelatinous, intensely beefy stew." },
  { foodId: "oxtail", alcoholId: "stout", reason: "Dark roasted malt echoes the depth of the slow-cooked oxtail." },

  // Seafood
  { foodId: "sushi", alcoholId: "sake", reason: "Clean umami character in sake elevates the delicate raw fish." },
  { foodId: "sushi", alcoholId: "white_wine", reason: "Crisp acidity mirrors the tang of pickled ginger and rice vinegar." },
  { foodId: "sushi", alcoholId: "riesling", reason: "Off-dry Riesling complements the sweetness of fresh fish and rice." },
  { foodId: "fish_and_chips", alcoholId: "lager", reason: "Cold lager and battered fish is a timeless British combination." },
  { foodId: "fish_and_chips", alcoholId: "cider", reason: "Apple acidity cuts through the batter and complements the mushy peas." },
  { foodId: "grilled_salmon", alcoholId: "chardonnay", reason: "Buttery oak notes mirror the richness of Atlantic salmon." },
  { foodId: "grilled_salmon", alcoholId: "sauvignon_blanc", reason: "Citrus and herbaceous notes lift the natural sweetness of salmon." },
  { foodId: "grilled_salmon", alcoholId: "pinot_noir", reason: "Light tannins pair elegantly with salmon without overpowering." },
  { foodId: "oysters", alcoholId: "champagne", reason: "Fine bubbles and sharp acidity amplify the briny oceanic freshness." },
  { foodId: "oysters", alcoholId: "sauvignon_blanc", reason: "Mineral crispness echoes the sea perfectly." },
  { foodId: "oysters", alcoholId: "gin_tonic", reason: "Herbaceous botanicals and tonic complement the brininess of oysters." },
  { foodId: "lobster", alcoholId: "chardonnay", reason: "Rich, buttery Chardonnay is the classic partner for sweet lobster." },
  { foodId: "lobster", alcoholId: "champagne", reason: "Champagne's elegance and acidity match the luxury of whole lobster." },
  { foodId: "shrimp_cocktail", alcoholId: "sauvignon_blanc", reason: "Crisp citrus notes lift the sweet prawns beautifully." },
  { foodId: "shrimp_cocktail", alcoholId: "prosecco", reason: "Fine bubbles and light acidity refresh between bites." },
  { foodId: "crab_cakes", alcoholId: "chardonnay", reason: "Creamy Chardonnay complements the delicate sweetness of crab." },
  { foodId: "crab_cakes", alcoholId: "sauvignon_blanc", reason: "Herbaceous crispness cuts through the rich remoulade." },
  { foodId: "tuna_steak", alcoholId: "rose_wine", reason: "Dry rosé bridges the meaty tuna and Mediterranean accompaniments." },
  { foodId: "tuna_steak", alcoholId: "sauvignon_blanc", reason: "Bright acidity cuts through the oily richness of seared tuna." },
  { foodId: "sea_bass", alcoholId: "white_wine", reason: "Crisp white wine enhances the delicate flavour of the fish." },
  { foodId: "sea_bass", alcoholId: "sauvignon_blanc", reason: "Citrus and mineral notes echo the fennel and capers." },
  { foodId: "mussels", alcoholId: "white_wine", reason: "What they're cooked in is what you drink — crisp white wine." },
  { foodId: "mussels", alcoholId: "wheat_beer", reason: "Yeasty, citrusy wheat beer complements the briny, brothy mussels." },
  { foodId: "clam_chowder", alcoholId: "chardonnay", reason: "Buttery Chardonnay mirrors the cream and sweetness of the clams." },
  { foodId: "clam_chowder", alcoholId: "cider", reason: "Apple acidity cuts through the rich, creamy New England broth." },
  { foodId: "scallops", alcoholId: "chardonnay", reason: "Oaked Chardonnay echoes the butter and matches the scallop's richness." },
  { foodId: "scallops", alcoholId: "champagne", reason: "Fine bubbles cleanse the palate between golden seared scallops." },
  { foodId: "calamari", alcoholId: "white_wine", reason: "Crisp white wine complements the light batter and lemon." },
  { foodId: "calamari", alcoholId: "rose_wine", reason: "Dry rosé bridges the seafood and the aioli dipping sauce." },
  { foodId: "smoked_salmon", alcoholId: "champagne", reason: "Champagne's acidity cuts through the richness of smoked salmon." },
  { foodId: "smoked_salmon", alcoholId: "sauvignon_blanc", reason: "Citrus crispness lifts the smoke and complements the crème fraîche." },
  { foodId: "ceviche", alcoholId: "sauvignon_blanc", reason: "Bright citrus notes echo the lime cure of the ceviche." },
  { foodId: "ceviche", alcoholId: "prosecco", reason: "Light bubbles and acidity complement the fresh, zingy flavours." },
  { foodId: "bouillabaisse", alcoholId: "white_wine", reason: "Provençal white wine ties together the saffron and seafood." },
  { foodId: "bouillabaisse", alcoholId: "rose_wine", reason: "Southern French rosé is the natural partner for this Marseille classic." },
  { foodId: "sashimi", alcoholId: "sake", reason: "Clean sake lets the purity and freshness of the fish shine." },
  { foodId: "sashimi", alcoholId: "riesling", reason: "Delicate acidity complements the clean flavours of raw fish." },
  { foodId: "lobster_bisque", alcoholId: "chardonnay", reason: "Buttery Chardonnay mirrors the cream and cognac in the bisque." },
  { foodId: "lobster_bisque", alcoholId: "cognac", reason: "The brandy in the bisque and in the glass creates perfect harmony." },
  { foodId: "lobster_thermidor", alcoholId: "chardonnay", reason: "Rich Chardonnay matches the mustard cream and grilled richness." },
  { foodId: "lobster_thermidor", alcoholId: "champagne", reason: "Champagne's elegance is worthy of this iconic French classic." },
  { foodId: "prawn_curry", alcoholId: "riesling", reason: "Off-dry Riesling tames the spice and complements the coconut." },
  { foodId: "prawn_curry", alcoholId: "lager", reason: "Cold lager soothes the heat and refreshes the palate." },
  { foodId: "fish_tacos", alcoholId: "margarita", reason: "Lime and tequila are natural partners for crispy fish tacos." },
  { foodId: "fish_tacos", alcoholId: "lager", reason: "Ice-cold lager cools the heat and complements the mango salsa." },

  // Italian
  { foodId: "pasta", alcoholId: "red_wine", reason: "Italian red wine and pasta is one of the great culinary partnerships." },
  { foodId: "pasta", alcoholId: "white_wine", reason: "Crisp white wine lifts cream-based sauces and lighter pasta dishes." },
  { foodId: "lasagna", alcoholId: "red_wine", reason: "A robust red matches the rich ragù and béchamel layers." },
  { foodId: "lasagna", alcoholId: "sangria", reason: "Fruity sangria complements the tomato and meat without competing." },
  { foodId: "risotto", alcoholId: "white_wine", reason: "Crisp white wine echoes the wine stirred into the risotto itself." },
  { foodId: "risotto", alcoholId: "champagne", reason: "Champagne's acidity cuts through the richness of butter and parmesan." },
  { foodId: "carbonara", alcoholId: "white_wine", reason: "A dry white cuts through the richness of egg, guanciale and pecorino." },
  { foodId: "carbonara", alcoholId: "chardonnay", reason: "Buttery Chardonnay mirrors the silky egg-yolk sauce beautifully." },
  { foodId: "gnocchi", alcoholId: "white_wine", reason: "Light white wine complements the delicate potato pillows." },
  { foodId: "gnocchi", alcoholId: "prosecco", reason: "Fine bubbles and acidity cut through the sage brown butter sauce." },
  { foodId: "tiramisu", alcoholId: "prosecco", reason: "Sparkling Prosecco lifts the richness of mascarpone and espresso." },
  { foodId: "tiramisu", alcoholId: "port", reason: "Rich port mirrors the depth of espresso and dark cocoa." },
  { foodId: "bruschetta", alcoholId: "prosecco", reason: "Sparkling Prosecco complements the fresh tomato and basil perfectly." },
  { foodId: "bruschetta", alcoholId: "sauvignon_blanc", reason: "Herbaceous crispness echoes the basil and fresh tomato topping." },
  { foodId: "spaghetti_bolognese", alcoholId: "red_wine", reason: "A medium Italian red is the natural companion for slow-cooked ragù." },
  { foodId: "spaghetti_bolognese", alcoholId: "sangria", reason: "Fruity sangria brings out the tomato richness in the bolognese." },
  { foodId: "pizza_margherita", alcoholId: "red_wine", reason: "Italian red wine and Neapolitan pizza is a classic combination." },
  { foodId: "pizza_margherita", alcoholId: "lager", reason: "Cold lager refreshes against the tangy tomato and creamy mozzarella." },
  { foodId: "burrata", alcoholId: "prosecco", reason: "Fine bubbles cut through the rich cream of the stracciatella." },
  { foodId: "burrata", alcoholId: "white_wine", reason: "Crisp white wine balances the indulgent creaminess of the burrata." },
  { foodId: "caprese", alcoholId: "rose_wine", reason: "Dry rosé complements the tomatoes, basil and buffalo mozzarella." },
  { foodId: "caprese", alcoholId: "prosecco", reason: "Light bubbles refresh between bites of this simple, perfect salad." },
  { foodId: "ravioli", alcoholId: "white_wine", reason: "Delicate white wine complements the ricotta and spinach filling." },
  { foodId: "ravioli", alcoholId: "chardonnay", reason: "Buttery Chardonnay echoes the sage brown butter sauce." },
  { foodId: "linguine_vongole", alcoholId: "white_wine", reason: "Crisp white mirrors the clam juices and white wine in the sauce." },
  { foodId: "linguine_vongole", alcoholId: "sauvignon_blanc", reason: "Mineral and citrus notes echo the briny clams and parsley." },
  { foodId: "squid_ink_risotto", alcoholId: "white_wine", reason: "Crisp white wine cuts through the intense, briny squid ink." },
  { foodId: "squid_ink_risotto", alcoholId: "prosecco", reason: "Fine bubbles and acidity balance the dramatic, umami-rich dish." },
  { foodId: "ossobuco_main", alcoholId: "red_wine", reason: "A full-bodied red complements the braised veal and gremolata." },
  { foodId: "ossobuco_main", alcoholId: "white_wine", reason: "Dry white echoes the braising liquid and balances the richness." },
  { foodId: "bistecca_fiorentina", alcoholId: "cabernet_sauvignon", reason: "Only a powerful Tuscan red can stand up to this enormous T-bone." },
  { foodId: "bistecca_fiorentina", alcoholId: "red_wine", reason: "A full Chianti Classico is the traditional pairing for Florentine steak." },
  { foodId: "cannoli", alcoholId: "prosecco", reason: "Sparkling Prosecco cuts through the sweet ricotta and pastry." },
  { foodId: "cannoli", alcoholId: "sherry", reason: "Nutty, sweet sherry echoes the candied peel and ricotta filling." },

  // Mexican
  { foodId: "tacos", alcoholId: "margarita", reason: "Lime and tequila are the natural partners for street-style tacos." },
  { foodId: "tacos", alcoholId: "lager", reason: "Ice-cold Mexican lager cools the heat and complements the salsa." },
  { foodId: "tacos", alcoholId: "tequila", reason: "Agave spirit echoes the smoky char and spiced meat beautifully." },
  { foodId: "enchiladas", alcoholId: "margarita", reason: "Lime acidity and tequila cut through the rich red chile sauce." },
  { foodId: "enchiladas", alcoholId: "lager", reason: "Cold lager refreshes against the spiced chicken and cheese." },
  { foodId: "quesadillas", alcoholId: "lager", reason: "Crisp lager cuts through the melted cheese and black beans." },
  { foodId: "quesadillas", alcoholId: "margarita", reason: "Citrusy margarita lifts the richness of the cheese filling." },
  { foodId: "guacamole", alcoholId: "margarita", reason: "Lime and tequila are made for avocado, chilli and coriander." },
  { foodId: "guacamole", alcoholId: "tequila", reason: "The earthiness of agave mirrors the creaminess of the avocado." },
  { foodId: "burritos", alcoholId: "lager", reason: "Cold lager cuts through the rice, beans, meat and sour cream." },
  { foodId: "burritos", alcoholId: "margarita", reason: "Citrus and tequila bring brightness to the heavy, satisfying burrito." },
  { foodId: "carne_asada", alcoholId: "mezcal", reason: "Smoky mezcal mirrors the char of the grilled skirt steak perfectly." },
  { foodId: "carne_asada", alcoholId: "red_wine", reason: "A spicy red wine complements the pico de gallo and charred meat." },
  { foodId: "birria_tacos", alcoholId: "lager", reason: "Cold lager refreshes between rich, consommé-dipped tacos." },
  { foodId: "birria_tacos", alcoholId: "mezcal", reason: "Smoky mezcal deepens the earthy, chile-braised beef." },
  { foodId: "taco_al_pastor", alcoholId: "lager", reason: "Mexican lager is the classic street-food partner for al pastor." },
  { foodId: "taco_al_pastor", alcoholId: "margarita", reason: "Pineapple and citrus in the margarita mirror the pastor's sweet char." },
  { foodId: "churros", alcoholId: "sherry", reason: "Nutty, sweet sherry is the classic Spanish partner for churros." },
  { foodId: "churros", alcoholId: "port", reason: "Rich port echoes the chocolate dipping sauce and cinnamon sugar." },

  // Asian
  { foodId: "pad_thai", alcoholId: "lager", reason: "Light lager refreshes against the tamarind, peanut and noodle richness." },
  { foodId: "pad_thai", alcoholId: "riesling", reason: "Off-dry Riesling tames the chilli heat and complements the sweetness." },
  { foodId: "ramen", alcoholId: "sake", reason: "Umami-rich sake deepens the complexity of the tonkotsu broth." },
  { foodId: "ramen", alcoholId: "lager", reason: "Crisp carbonation cuts through the fatty, rich ramen broth." },
  { foodId: "dumplings", alcoholId: "sake", reason: "Subtle grain notes in sake balance the savoury pork filling." },
  { foodId: "dumplings", alcoholId: "lager", reason: "Cold lager cuts through the richness of the fried dumpling wrappers." },
  { foodId: "pho", alcoholId: "lager", reason: "Refreshing lager complements the clean, aromatic star anise broth." },
  { foodId: "pho", alcoholId: "riesling", reason: "Floral Riesling echoes the fragrant spices of the Vietnamese broth." },
  { foodId: "bibimbap", alcoholId: "sake", reason: "Clean sake lets the varied namul and gochujang flavours shine." },
  { foodId: "bibimbap", alcoholId: "lager", reason: "Cold lager refreshes against the spiced rice bowl." },
  { foodId: "bulgogi", alcoholId: "sake", reason: "Clean sake complements the sweet, sesame-marinated beef." },
  { foodId: "bulgogi", alcoholId: "red_wine", reason: "A light red wine ties together the sweet and savoury Korean flavours." },
  { foodId: "green_curry", alcoholId: "riesling", reason: "Off-dry Riesling is the classic partner for Thai green curry heat." },
  { foodId: "green_curry", alcoholId: "lager", reason: "Cold lager soothes the fiery green chilli paste." },
  { foodId: "satay", alcoholId: "lager", reason: "Cold lager refreshes between skewers and cuts the peanut sauce." },
  { foodId: "satay", alcoholId: "riesling", reason: "Fruity Riesling mirrors the peanut and palm sugar in the sauce." },
  { foodId: "banh_mi", alcoholId: "lager", reason: "Crisp lager complements the pickled daikon, chilli and pâté." },
  { foodId: "banh_mi", alcoholId: "sauvignon_blanc", reason: "Herbaceous crispness echoes the coriander and lime in the baguette." },
  { foodId: "rendang", alcoholId: "lager", reason: "Cold lager cuts through the rich, dried-down coconut curry." },
  { foodId: "rendang", alcoholId: "red_wine", reason: "A full-bodied red complements the lemongrass and slow-cooked beef." },
  { foodId: "korean_fried_chicken", alcoholId: "lager", reason: "Cold Korean lager is the classic partner for crispy fried chicken." },
  { foodId: "korean_fried_chicken", alcoholId: "sake", reason: "Clean sake lets the soy garlic glaze and crunch shine through." },
  { foodId: "gyoza", alcoholId: "sake", reason: "Sake's umami depth complements the ginger pork filling perfectly." },
  { foodId: "gyoza", alcoholId: "lager", reason: "Crisp lager cuts through the crispy base and rich dipping sauce." },
  { foodId: "dim_sum", alcoholId: "sake", reason: "Clean sake complements the delicate steamed and fried dumplings." },
  { foodId: "dim_sum", alcoholId: "champagne", reason: "Champagne's bubbles and acidity refresh between the varied dishes." },
  { foodId: "peking_duck", alcoholId: "pinot_noir", reason: "Light-bodied Pinot Noir is the classic wine match for duck." },
  { foodId: "peking_duck", alcoholId: "sake", reason: "Clean sake complements the lacquered skin and hoisin sauce." },

  // Indian
  { foodId: "butter_chicken", alcoholId: "riesling", reason: "Off-dry Riesling tames the spice and complements the cream sauce." },
  { foodId: "butter_chicken", alcoholId: "lager", reason: "Cold lager soothes the heat and refreshes the creamy tomato sauce." },
  { foodId: "biryani", alcoholId: "riesling", reason: "Floral Riesling echoes the saffron and complements the aromatic spices." },
  { foodId: "biryani", alcoholId: "rose_wine", reason: "Dry rosé bridges the fragrant spices and tender lamb." },
  { foodId: "chana_masala", alcoholId: "lager", reason: "Cold lager refreshes against the tangy, spiced chickpea curry." },
  { foodId: "chana_masala", alcoholId: "riesling", reason: "Off-dry Riesling complements the amchur and spiced tomato sauce." },
  { foodId: "vindaloo", alcoholId: "ipa", reason: "Bold hop bitterness is one of the few things that can stand up to vindaloo." },
  { foodId: "vindaloo", alcoholId: "lager", reason: "Ice-cold lager is the classic antidote to the fierce Goan chilli heat." },
  { foodId: "tikka_masala", alcoholId: "riesling", reason: "Off-dry Riesling tames the smoky spice and mirrors the cream." },
  { foodId: "tikka_masala", alcoholId: "lager", reason: "Cold lager soothes the spice and complements the charred chicken." },
  { foodId: "rogan_josh", alcoholId: "red_wine", reason: "A spiced red wine complements the Kashmiri chilli and whole spices." },
  { foodId: "rogan_josh", alcoholId: "lager", reason: "Cold lager refreshes against the intense, aromatic lamb curry." },
  { foodId: "tandoori_chicken", alcoholId: "rose_wine", reason: "Dry rosé complements the yoghurt marinade and charred tikka spices." },
  { foodId: "tandoori_chicken", alcoholId: "riesling", reason: "Fruity Riesling echoes the cumin and coriander of the tandoor spices." },
  { foodId: "samosas", alcoholId: "lager", reason: "Cold lager refreshes against the spiced potato and crispy pastry." },
  { foodId: "samosas", alcoholId: "chardonnay", reason: "Buttery Chardonnay complements the peas and potato filling." },
  { foodId: "seekh_kebab", alcoholId: "lager", reason: "Cold lager cuts through the spiced minced lamb on the skewer." },
  { foodId: "seekh_kebab", alcoholId: "red_wine", reason: "A medium red wine complements the green chilli and cumin spicing." },

  // Middle Eastern
  { foodId: "hummus", alcoholId: "rose_wine", reason: "Dry rosé complements the tahini and lemon of the hummus." },
  { foodId: "hummus", alcoholId: "white_wine", reason: "Crisp white wine lifts the richness of the olive oil and chickpeas." },
  { foodId: "falafel", alcoholId: "lager", reason: "Cold lager refreshes against the crispy, herb-flecked chickpea patties." },
  { foodId: "falafel", alcoholId: "rose_wine", reason: "Dry rosé ties together the tahini, pickles and fresh herbs." },
  { foodId: "shawarma", alcoholId: "lager", reason: "Cold lager cuts through the garlic sauce and spiced lamb." },
  { foodId: "shawarma", alcoholId: "red_wine", reason: "A medium red wine complements the charred, spiced rotisserie meat." },
  { foodId: "kebab", alcoholId: "lager", reason: "Cold lager is the classic partner for chargrilled lamb kofta." },
  { foodId: "kebab", alcoholId: "red_wine", reason: "Spiced red wine mirrors the allspice and sumac of the kebab." },
  { foodId: "shakshuka", alcoholId: "rose_wine", reason: "Dry rosé complements the spiced tomato sauce and poached eggs." },
  { foodId: "shakshuka", alcoholId: "bloody_mary", reason: "Tomato and spice in both dish and glass create perfect harmony." },
  { foodId: "mezze", alcoholId: "rose_wine", reason: "Dry rosé bridges the hummus, olives, vine leaves and warm bread." },
  { foodId: "mezze", alcoholId: "white_wine", reason: "Crisp white wine complements the varied dips and flatbreads." },
  { foodId: "baklava", alcoholId: "sherry", reason: "Nutty, sweet sherry mirrors the pistachio and rose water syrup." },
  { foodId: "baklava", alcoholId: "port", reason: "Rich port complements the honey, nuts and layered filo pastry." },

  // Spanish
  { foodId: "paella", alcoholId: "white_wine", reason: "Spanish white wine echoes the saffron and brightens the seafood." },
  { foodId: "paella", alcoholId: "sangria", reason: "Fruity sangria is the quintessential Spanish partner for paella." },
  { foodId: "paella", alcoholId: "rose_wine", reason: "Dry Spanish rosé bridges the chicken, shellfish and saffron rice." },
  { foodId: "tapas", alcoholId: "sherry", reason: "Fino sherry is the classic Andalusian partner for tapas." },
  { foodId: "tapas", alcoholId: "sangria", reason: "Fruity sangria ties together the varied flavours of a tapas spread." },
  { foodId: "gazpacho", alcoholId: "sherry", reason: "Fino sherry echoes the Andalusian origins and complements the tomato." },
  { foodId: "gazpacho", alcoholId: "rose_wine", reason: "Chilled rosé mirrors the cold soup's freshness and acidity." },
  { foodId: "patatas_bravas", alcoholId: "lager", reason: "Cold Spanish lager cuts through the spicy brava sauce and oil." },
  { foodId: "patatas_bravas", alcoholId: "sangria", reason: "Fruity sangria complements the crispy potatoes and smoky paprika." },
  { foodId: "gambas_al_ajillo", alcoholId: "white_wine", reason: "Crisp white mirrors the garlic, olive oil and sherry in the pan." },
  { foodId: "gambas_al_ajillo", alcoholId: "sherry", reason: "Manzanilla sherry echoes the sherry used to cook the prawns." },
  { foodId: "croquetas", alcoholId: "sherry", reason: "Fino sherry cuts through the rich béchamel and jamón filling." },
  { foodId: "croquetas", alcoholId: "lager", reason: "Cold lager refreshes against the crispy, creamy croquetas." },

  // Healthy
  { foodId: "caesar_salad", alcoholId: "chardonnay", reason: "Oaked Chardonnay complements the creamy anchovy dressing." },
  { foodId: "caesar_salad", alcoholId: "sauvignon_blanc", reason: "Crisp acidity cuts through the rich dressing and parmesan." },
  { foodId: "quinoa_bowl", alcoholId: "sauvignon_blanc", reason: "Herbaceous crispness complements the tahini and roasted vegetables." },
  { foodId: "quinoa_bowl", alcoholId: "rose_wine", reason: "Dry rosé bridges the avocado, grains and citrus dressing." },
  { foodId: "nicoise_salad", alcoholId: "rose_wine", reason: "Provençal rosé is the classic partner for this Niçoise classic." },
  { foodId: "nicoise_salad", alcoholId: "sauvignon_blanc", reason: "Crisp white complements the tuna, beans and anchovy dressing." },
  { foodId: "greek_salad", alcoholId: "rose_wine", reason: "Dry rosé complements the feta, olives and ripe tomatoes." },
  { foodId: "greek_salad", alcoholId: "white_wine", reason: "Crisp white wine lifts the lemon dressing and Mediterranean flavours." },
  { foodId: "poke_bowl", alcoholId: "sake", reason: "Clean sake echoes the soy and sesame oil dressing on the tuna." },
  { foodId: "poke_bowl", alcoholId: "sauvignon_blanc", reason: "Citrus crispness complements the fresh fish and pickled cucumber." },
  { foodId: "lentil_soup", alcoholId: "red_wine", reason: "A medium red wine complements the cumin and earthy lentils." },
  { foodId: "lentil_soup", alcoholId: "lager", reason: "Cold lager refreshes against the warm, spiced lentil soup." },

  // Breakfast
  { foodId: "full_english", alcoholId: "bloody_mary", reason: "Spiced tomato juice is the ultimate companion for a full English." },
  { foodId: "full_english", alcoholId: "stout", reason: "Dark roasted stout echoes the bacon and sausage richness." },
  { foodId: "eggs_benedict", alcoholId: "champagne", reason: "Champagne's acidity cuts through the hollandaise and poached egg." },
  { foodId: "eggs_benedict", alcoholId: "mimosa", reason: "Orange and champagne is the classic brunch partner for Eggs Benedict." },
  { foodId: "pancakes", alcoholId: "mimosa", reason: "Orange and champagne is the quintessential brunch pairing." },
  { foodId: "pancakes", alcoholId: "champagne", reason: "Fine bubbles and acidity cut through the butter and maple syrup." },
  { foodId: "french_toast", alcoholId: "mimosa", reason: "Citrusy mimosa complements the custard-soaked, powdered brioche." },
  { foodId: "french_toast", alcoholId: "champagne", reason: "Champagne's acidity balances the rich, sweet French toast." },
  { foodId: "waffles", alcoholId: "mimosa", reason: "Bright orange and bubbles are perfect for a waffle brunch." },
  { foodId: "waffles", alcoholId: "prosecco", reason: "Light Prosecco cuts through the cream and caramelised banana." },
  { foodId: "smoked_salmon_bagel", alcoholId: "champagne", reason: "Champagne's crisp acidity cuts through the smoked salmon and cream cheese." },
  { foodId: "smoked_salmon_bagel", alcoholId: "bloody_mary", reason: "Spiced tomato mirrors the smoke and complements the capers." },
  { foodId: "croque_monsieur", alcoholId: "white_wine", reason: "Crisp Chablis cuts through the béchamel and Gruyère." },
  { foodId: "croque_monsieur", alcoholId: "champagne", reason: "Fine bubbles and acidity balance the rich, melted cheese topping." },
  { foodId: "omelette", alcoholId: "champagne", reason: "Champagne's bubbles and acidity complement the delicate egg." },
  { foodId: "omelette", alcoholId: "white_wine", reason: "A crisp white wine lifts the herbs and cheese in the filling." },
  { foodId: "chilaquiles", alcoholId: "bloody_mary", reason: "Spiced tomato and heat in both dish and glass create perfect harmony." },
  { foodId: "chilaquiles", alcoholId: "margarita", reason: "Lime and tequila bring brightness to the salsa verde and cream." },

  // Snacks
  { foodId: "cheese_board", alcoholId: "red_wine", reason: "A medium red wine complements aged hard cheeses beautifully." },
  { foodId: "cheese_board", alcoholId: "champagne", reason: "Fine bubbles and acidity cut through the richness of soft cheeses." },
  { foodId: "cheese_board", alcoholId: "port", reason: "Rich port is the classic partner for blue and aged cheeses." },
  { foodId: "charcuterie", alcoholId: "red_wine", reason: "A light red brings out the savoury depth of cured meats." },
  { foodId: "charcuterie", alcoholId: "rose_wine", reason: "Dry rosé bridges the fat of the charcuterie and the cornichons." },
  { foodId: "pretzels", alcoholId: "lager", reason: "Cold lager and salted pretzels is a timeless German pairing." },
  { foodId: "pretzels", alcoholId: "wheat_beer", reason: "Yeasty wheat beer echoes the doughy, baked pretzel perfectly." },
  { foodId: "devilled_eggs", alcoholId: "champagne", reason: "Fine bubbles complement the smoky paprika and mayo filling." },
  { foodId: "devilled_eggs", alcoholId: "bloody_mary", reason: "Spiced tomato and devilled eggs are a natural brunch combination." },
  { foodId: "olives", alcoholId: "martini", reason: "The olive in the martini and on the plate are a natural pairing." },
  { foodId: "olives", alcoholId: "sherry", reason: "Fino sherry and olives is a classic Andalusian aperitivo combination." },
  { foodId: "scotch_eggs", alcoholId: "pale_ale", reason: "Malt body and gentle bitterness complement the sausagemeat casing." },
  { foodId: "scotch_eggs", alcoholId: "cider", reason: "Apple acidity cuts through the richness of the fried sausagemeat." },
  { foodId: "pate_toast", alcoholId: "port", reason: "Rich port is the traditional pairing for silky chicken liver pâté." },
  { foodId: "pate_toast", alcoholId: "champagne", reason: "Champagne's acidity cuts through the richness of the pâté." },
  { foodId: "antipasto", alcoholId: "prosecco", reason: "Sparkling Prosecco is the ideal aperitivo partner for antipasto." },
  { foodId: "antipasto", alcoholId: "red_wine", reason: "A light Italian red ties together the cured meats and marinated vegetables." },

  // Dessert
  { foodId: "chocolate_cake", alcoholId: "port", reason: "Rich dried fruit in port mirrors the depth of dark chocolate." },
  { foodId: "chocolate_cake", alcoholId: "stout", reason: "Roasted malt in stout echoes the intense dark chocolate perfectly." },
  { foodId: "chocolate_cake", alcoholId: "whiskey", reason: "Smoky caramel warmth in whiskey complements bittersweet cocoa." },
  { foodId: "creme_brulee", alcoholId: "champagne", reason: "Fine bubbles and acidity contrast beautifully with the set custard." },
  { foodId: "creme_brulee", alcoholId: "cognac", reason: "French brandy echoes the vanilla and caramelised sugar crust." },
  { foodId: "cheesecake", alcoholId: "prosecco", reason: "Light Prosecco cuts through the rich cream cheese filling." },
  { foodId: "cheesecake", alcoholId: "sherry", reason: "Sweet sherry complements the digestive base and vanilla cream." },
  { foodId: "apple_pie", alcoholId: "cider", reason: "Apple cider and apple pie echo each other in perfect harmony." },
  { foodId: "apple_pie", alcoholId: "bourbon", reason: "Vanilla and caramel in bourbon mirror the cinnamon apple filling." },
  { foodId: "sticky_toffee_pudding", alcoholId: "port", reason: "Rich port mirrors the dark toffee sauce and date sponge." },
  { foodId: "sticky_toffee_pudding", alcoholId: "whiskey", reason: "Caramel notes in whiskey complement the sticky, dark toffee sauce." },
  { foodId: "tarte_tatin", alcoholId: "champagne", reason: "Champagne's acidity balances the rich caramelised apple tart." },
  { foodId: "tarte_tatin", alcoholId: "cognac", reason: "French brandy echoes the caramel and butter of the tarte." },
  { foodId: "pavlova", alcoholId: "prosecco", reason: "Light Prosecco complements the crisp meringue and fresh berries." },
  { foodId: "pavlova", alcoholId: "champagne", reason: "Champagne's elegance matches the delicate cream and passion fruit." },
  { foodId: "mousse_au_chocolat", alcoholId: "port", reason: "Rich port mirrors the airy dark chocolate and whipped cream." },
  { foodId: "mousse_au_chocolat", alcoholId: "stout", reason: "Roasted malt depth echoes the bittersweet chocolate mousse." },

  // Greek
  { foodId: "moussaka", alcoholId: "red_wine", reason: "A robust red complements the spiced lamb and béchamel layers." },
  { foodId: "moussaka", alcoholId: "sangria", reason: "Fruity sangria brings out the tomato and cinnamon in the mince." },
  { foodId: "souvlaki", alcoholId: "lager", reason: "Cold lager refreshes against the chargrilled pork and tzatziki." },
  { foodId: "souvlaki", alcoholId: "rose_wine", reason: "Dry rosé echoes the Mediterranean herbs and lemon of the skewers." },
  { foodId: "spanakopita", alcoholId: "white_wine", reason: "Crisp white wine complements the spinach, feta and flaky filo." },
  { foodId: "spanakopita", alcoholId: "rose_wine", reason: "Dry rosé bridges the salty feta and buttery pastry layers." },
  { foodId: "kleftiko", alcoholId: "red_wine", reason: "A full-bodied red stands up to the slow-baked lamb and garlic." },
  { foodId: "kleftiko", alcoholId: "cabernet_sauvignon", reason: "Bold tannins complement the rich, meltingly tender lamb shank." },
  { foodId: "saganaki", alcoholId: "white_wine", reason: "Crisp white wine cuts through the golden, squeaky fried cheese." },
  { foodId: "saganaki", alcoholId: "prosecco", reason: "Fine bubbles refresh against the salty, pan-fried cheese." },

  // French
  { foodId: "french_onion_soup", alcoholId: "white_wine", reason: "Dry white wine echoes the wine in the broth and cuts the Gruyère." },
  { foodId: "french_onion_soup", alcoholId: "red_wine", reason: "A light red complements the caramelised onion depth." },
  { foodId: "duck_confit", alcoholId: "pinot_noir", reason: "Silky Pinot Noir is the classic partner for slow-cooked duck leg." },
  { foodId: "duck_confit", alcoholId: "red_wine", reason: "Earthy red wine brings out the richness of the confit duck." },
  { foodId: "boeuf_bourguignon", alcoholId: "red_wine", reason: "What's cooked in it is what you drink — Burgundy is the match." },
  { foodId: "boeuf_bourguignon", alcoholId: "pinot_noir", reason: "Pinot Noir's earthiness mirrors the mushrooms and slow-braised beef." },
  { foodId: "escargot", alcoholId: "white_wine", reason: "Crisp white wine echoes the parsley garlic butter of the snails." },
  { foodId: "escargot", alcoholId: "champagne", reason: "Champagne's acidity cuts through the rich, garlicky butter." },
  { foodId: "foie_gras", alcoholId: "sherry", reason: "Sweet-nutty sherry is a classic match for the rich liver." },
  { foodId: "foie_gras", alcoholId: "champagne", reason: "Champagne's acidity cuts through the extraordinary richness." },
  { foodId: "quiche_lorraine", alcoholId: "white_wine", reason: "Crisp white mirrors the egg custard and complements the lardons." },
  { foodId: "quiche_lorraine", alcoholId: "chardonnay", reason: "Buttery Chardonnay echoes the cream and smoky bacon." },
  { foodId: "steak_frites", alcoholId: "red_wine", reason: "A robust red wine is the Parisian bistro partner for steak frites." },
  { foodId: "steak_frites", alcoholId: "malbec", reason: "Dark fruit in Malbec complements the char of the bavette." },
  { foodId: "cassoulet", alcoholId: "red_wine", reason: "A hearty southern French red stands up to the duck and sausage." },
  { foodId: "cassoulet", alcoholId: "cabernet_sauvignon", reason: "Bold tannins and dark fruit complement this rich, slow-baked stew." },
  { foodId: "tartiflette", alcoholId: "white_wine", reason: "Crisp Alpine white wine cuts through the Reblochon and lardons." },
  { foodId: "tartiflette", alcoholId: "chardonnay", reason: "Buttery Chardonnay mirrors the melted cheese and potato richness." },

  // Japanese
  { foodId: "tonkatsu", alcoholId: "lager", reason: "Cold lager cuts through the panko crust and rich tonkatsu sauce." },
  { foodId: "tonkatsu", alcoholId: "sake", reason: "Clean sake complements the pork and the shredded cabbage garnish." },
  { foodId: "yakitori", alcoholId: "sake", reason: "Clean sake lets the charcoal and tare sauce of the skewers shine." },
  { foodId: "yakitori", alcoholId: "lager", reason: "Cold lager refreshes between smoky, sweet-glazed chicken skewers." },
  { foodId: "katsu_curry", alcoholId: "lager", reason: "Cold lager cuts through the rich Japanese curry sauce and panko." },
  { foodId: "katsu_curry", alcoholId: "sake", reason: "Clean sake complements the mild, sweet curry and crispy chicken." },
  { foodId: "udon", alcoholId: "sake", reason: "Sake's umami mirrors the dashi broth and complements the thick noodles." },
  { foodId: "udon", alcoholId: "lager", reason: "Cold lager refreshes against the warm, savoury noodle soup." },
  { foodId: "gyoza_jp", alcoholId: "sake", reason: "Sake's clean depth complements the ginger and pork filling." },
  { foodId: "gyoza_jp", alcoholId: "lager", reason: "Crisp lager cuts through the crispy base and ponzu dipping sauce." },
  { foodId: "shabu_shabu", alcoholId: "sake", reason: "Delicate sake complements the clean, light kombu broth." },
  { foodId: "shabu_shabu", alcoholId: "white_wine", reason: "Crisp white wine echoes the sesame dipping sauce and fresh vegetables." },
  { foodId: "karaage", alcoholId: "lager", reason: "Cold lager cuts through the crispy, ginger-soy fried chicken." },
  { foodId: "karaage", alcoholId: "sake", reason: "Clean sake lets the umami marinade and crispy skin shine." },
  { foodId: "zaru_soba", alcoholId: "sake", reason: "Clean sake complements the chilled noodles and tsuyu broth." },
  { foodId: "zaru_soba", alcoholId: "riesling", reason: "Floral Riesling echoes the delicate buckwheat and dashi notes." },

  // American
  { foodId: "mac_cheese", alcoholId: "lager", reason: "Cold lager cuts through the rich, three-cheese sauce." },
  { foodId: "mac_cheese", alcoholId: "chardonnay", reason: "Buttery Chardonnay mirrors the cream and cheddar in the sauce." },
  { foodId: "bbq_pulled_pork", alcoholId: "bourbon", reason: "Vanilla and caramel in bourbon mirror the sweet smoky pork." },
  { foodId: "bbq_pulled_pork", alcoholId: "lager", reason: "Cold lager cuts through the richness and refreshes the palate." },
  { foodId: "lobster_roll", alcoholId: "chardonnay", reason: "Buttery Chardonnay is the classic New England partner for lobster." },
  { foodId: "lobster_roll", alcoholId: "sauvignon_blanc", reason: "Crisp citrus notes complement the mayo-dressed lobster." },
  { foodId: "smoked_brisket", alcoholId: "bourbon", reason: "Oak and vanilla in bourbon mirror the smoke of Texas brisket." },
  { foodId: "smoked_brisket", alcoholId: "stout", reason: "Roasted malt echoes the dark peppercorn bark of the brisket." },
  { foodId: "reuben_sandwich", alcoholId: "lager", reason: "Cold lager cuts through the corned beef, cheese and sauerkraut." },
  { foodId: "reuben_sandwich", alcoholId: "stout", reason: "Dark malt depth echoes the richness of the corned beef and Swiss." },
  { foodId: "gumbo", alcoholId: "lager", reason: "Cold lager refreshes against the spiced, rich roux-based stew." },
  { foodId: "gumbo", alcoholId: "bourbon", reason: "Caramel warmth in bourbon mirrors the deep, dark roux of the gumbo." },

  // Barbecue
  { foodId: "bbq_chicken", alcoholId: "lager", reason: "Cold lager is the quintessential backyard barbecue partner." },
  { foodId: "bbq_chicken", alcoholId: "bourbon", reason: "Caramel and smoke in bourbon echo the charred, glazed chicken." },
  { foodId: "spare_ribs", alcoholId: "bourbon", reason: "Vanilla and oak in bourbon complement the dry rub and smoke." },
  { foodId: "spare_ribs", alcoholId: "stout", reason: "Roasted malt echoes the smoke and dark crust of the spare ribs." },
  { foodId: "burnt_ends", alcoholId: "bourbon", reason: "Rich caramel notes in bourbon are perfect for these sticky cubes." },
  { foodId: "burnt_ends", alcoholId: "stout", reason: "Dark, roasted malt depth is a worthy match for the holy grail of BBQ." },
  { foodId: "smoked_sausage", alcoholId: "lager", reason: "Cold lager refreshes against the smoky, spiced kielbasa." },
  { foodId: "smoked_sausage", alcoholId: "pale_ale", reason: "Malt sweetness complements the hickory smoke and fennel spice." },
  { foodId: "smoked_wings", alcoholId: "lager", reason: "Cold lager cuts through the Alabama white sauce and smoke." },
  { foodId: "smoked_wings", alcoholId: "pale_ale", reason: "Gentle hop bitterness complements the cold-smoked chicken." },

  // Caribbean
  { foodId: "jerk_chicken", alcoholId: "rum", reason: "Caribbean rum is the natural partner for pimento wood jerk chicken." },
  { foodId: "jerk_chicken", alcoholId: "lager", reason: "Ice-cold lager soothes the scotch bonnet heat beautifully." },
  { foodId: "curry_goat", alcoholId: "lager", reason: "Cold lager refreshes against the scotch bonnet and warm spices." },
  { foodId: "curry_goat", alcoholId: "rum", reason: "Caribbean rum ties together the island spices and slow-stewed goat." },
  { foodId: "plantain", alcoholId: "rum", reason: "Sweet rum mirrors the caramelised sugar of the fried plantain." },
  { foodId: "plantain", alcoholId: "lager", reason: "Cold lager refreshes against the sweet, sticky plantain." },

  // German
  { foodId: "bratwurst", alcoholId: "lager", reason: "Cold Bavarian lager is the timeless partner for grilled bratwurst." },
  { foodId: "bratwurst", alcoholId: "wheat_beer", reason: "Yeasty, citrusy wheat beer echoes the fennel and herbs in the sausage." },
  { foodId: "schnitzel", alcoholId: "lager", reason: "Cold lager cuts through the breadcrumb crust and pan-fried veal." },
  { foodId: "schnitzel", alcoholId: "white_wine", reason: "Crisp Austrian white wine is the traditional partner for Schnitzel." },
  { foodId: "sauerbraten", alcoholId: "red_wine", reason: "A full red complements the vinegar-marinated pot-roasted beef." },
  { foodId: "sauerbraten", alcoholId: "lager", reason: "Cold lager cuts through the rich, gingerbread gravy." },
  { foodId: "currywurst", alcoholId: "lager", reason: "Berlin lager and currywurst is one of Germany's great street-food pairings." },
  { foodId: "currywurst", alcoholId: "pale_ale", reason: "Malt sweetness complements the curry ketchup powder and sausage." },
  { foodId: "black_forest_cake", alcoholId: "port", reason: "Rich port mirrors the morello cherries and dark chocolate." },
  { foodId: "black_forest_cake", alcoholId: "whiskey", reason: "Caramel warmth in whiskey complements the cream and Kirsch." },

  // South American
  { foodId: "asado", alcoholId: "malbec", reason: "Argentine Malbec is the soul mate for an Argentine asado." },
  { foodId: "asado", alcoholId: "cabernet_sauvignon", reason: "Bold tannins stand up to the smoke and char of open-fire beef." },
  { foodId: "empanadas", alcoholId: "red_wine", reason: "A medium red wine complements the spiced beef and pastry." },
  { foodId: "empanadas", alcoholId: "lager", reason: "Cold lager refreshes against the crispy, stuffed pastry pockets." },
  { foodId: "ceviche_peruvian", alcoholId: "sauvignon_blanc", reason: "Citrus crispness echoes the tiger's milk and aji amarillo." },
  { foodId: "ceviche_peruvian", alcoholId: "prosecco", reason: "Fine bubbles and acidity complement the fresh, zingy ceviche." },
  { foodId: "feijoada", alcoholId: "red_wine", reason: "A robust red stands up to the rich black bean and pork stew." },
  { foodId: "feijoada", alcoholId: "lager", reason: "Cold Brazilian lager cuts through the richness of the feijoada." },

  // Eastern European
  { foodId: "pierogi", alcoholId: "vodka", reason: "Polish vodka and pierogi is one of Eastern Europe's great pairings." },
  { foodId: "pierogi", alcoholId: "lager", reason: "Cold lager cuts through the buttery potato and cheese filling." },
  { foodId: "borscht", alcoholId: "vodka", reason: "A shot of vodka alongside borscht is a classic Eastern European tradition." },
  { foodId: "borscht", alcoholId: "red_wine", reason: "Earthy red wine complements the deep, sweet beetroot flavours." },
  { foodId: "goulash", alcoholId: "red_wine", reason: "A spiced red wine mirrors the sweet paprika and caraway." },
  { foodId: "goulash", alcoholId: "lager", reason: "Cold lager refreshes against the rich, paprika-spiced beef stew." },
  { foodId: "stroganoff", alcoholId: "vodka", reason: "Russian vodka is the traditional spirit alongside beef Stroganoff." },
  { foodId: "stroganoff", alcoholId: "red_wine", reason: "A light red wine complements the sour cream and mustard sauce." },
  { foodId: "blini", alcoholId: "vodka", reason: "Ice-cold vodka is the classic Russian partner for blini and caviar." },
  { foodId: "blini", alcoholId: "champagne", reason: "Champagne's bubbles and acidity complement the sour cream topping." },

  // Cajun
  { foodId: "jambalaya", alcoholId: "lager", reason: "Cold lager cuts through the spiced andouille and holy trinity." },
  { foodId: "jambalaya", alcoholId: "bourbon", reason: "Caramel warmth in bourbon mirrors the smoky, spiced one-pot rice." },
  { foodId: "etouffe", alcoholId: "lager", reason: "Cold lager refreshes against the rich butter roux and crawfish." },
  { foodId: "etouffe", alcoholId: "chardonnay", reason: "Buttery Chardonnay echoes the rich butter sauce over the crawfish." },
  { foodId: "red_beans_rice", alcoholId: "lager", reason: "Cold lager cuts through the creamy red beans and andouille." },
  { foodId: "red_beans_rice", alcoholId: "bourbon", reason: "Caramel notes in bourbon mirror the smoky depth of the Creole spices." },
  { foodId: "po_boy", alcoholId: "lager", reason: "Cold lager is the classic New Orleans partner for a po'boy." },
  { foodId: "po_boy", alcoholId: "bloody_mary", reason: "Spiced tomato juice complements the fried shrimp and remoulade." },

  // Vegetarian
  { foodId: "mushroom_risotto", alcoholId: "white_wine", reason: "Crisp white echoes the wine stirred into the mushroom risotto." },
  { foodId: "mushroom_risotto", alcoholId: "pinot_noir", reason: "Earthy Pinot Noir mirrors the wild mushrooms and truffle oil." },
  { foodId: "veggie_burger", alcoholId: "lager", reason: "Cold lager is just as good with a beetroot patty as a beef one." },
  { foodId: "veggie_burger", alcoholId: "pale_ale", reason: "Malt sweetness complements the black bean and chipotle mayo." },
  { foodId: "cauliflower_steak", alcoholId: "white_wine", reason: "Crisp white wine complements the roasted harissa and pomegranate." },
  { foodId: "cauliflower_steak", alcoholId: "sauvignon_blanc", reason: "Herbaceous crispness echoes the charred cauliflower and herbs." },
  { foodId: "lentil_dhal", alcoholId: "lager", reason: "Cold lager soothes the mustard seeds and curry leaf tarka." },
  { foodId: "lentil_dhal", alcoholId: "riesling", reason: "Off-dry Riesling tames the spice and complements the lentils." },
  { foodId: "shakshuka_v", alcoholId: "rose_wine", reason: "Dry rosé complements the harissa-spiked tomato and poached eggs." },
  { foodId: "shakshuka_v", alcoholId: "bloody_mary", reason: "Spiced tomato in both dish and glass creates perfect harmony." },
];

async function seed() {
  console.log("Seeding foods...");
  for (const food of foods) {
    await db.collection("foods").doc(food.id).set({
      name: food.name,
      category: food.category,
    });
  }

  console.log("Seeding alcohols...");
  for (const alcohol of alcohols) {
    await db.collection("alcohols").doc(alcohol.id).set({
      name: alcohol.name,
      type: alcohol.type,
    });
  }

  console.log("Seeding pairings...");
  // Clear old pairings first
  const existing = await db.collection("pairings").get();
  for (const doc of existing.docs) {
    await doc.ref.delete();
  }
  for (const pairing of pairings) {
    await db.collection("pairings").add(pairing);
  }

  console.log(`✅ Done — ${foods.length} foods, ${alcohols.length} alcohols, ${pairings.length} pairings`);
  process.exit(0);
}

seed().catch((err) => { console.error(err); process.exit(1); });
